language: node_js
node_js:
  - "14"
cache:
  directories:
    - node_modules

before_install:
- cd src/frontend

jobs:
  include:
    - stage: Lint, Test, Build
    - name: Lint
      script:
        - npm install
        - npm run lint
        - cd ../backend
        - npm install
        - npm run lint
    - name: Test
      script:
        - npm install
        - npm test -- --coverage
	- cd ../backend
	- npm install
	- npm run test
    - name: Build
      script: 
        - npm install
        - npm run build
